services:
    dynamodb-local:
        command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
        image: 'amazon/dynamodb-local:latest'
        container_name: dynamodb-local
        ports:
            - '8000:8000'
        volumes:
            - './docker/dynamodb:/home/dynamodblocal/data'
        working_dir: /home/dynamodblocal
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'wget --no-verbose --tries=1 --spider http://localhost:8000 || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 5
            start_period: 10s
