services:
    dynamodb-local:
        image: amazon/dynamodb-local:latest
        command: '-jar DynamoDBLocal.jar -sharedDb -Djava.library.path=/DynamoDBLocal_lib -Dstreams.enabled=true'
        ports:
            - 8000:8000
        volumes:
            - './docker/dynamodb:/home/dynamodblocal/data'
        working_dir: /home/dynamodblocal
