import { render, screen } from '@testing-library/react'
import { TripHeader } from './TripHeader'
import { MemoryRouter } from 'react-router'

test('renders a SignUp CTA if the trip has been generated by a guest visitor', () => {
    render(
        <MemoryRouter initialEntries={['/trip/1']}>
            <TripHeader
                tripName="Test Trip"
                userId={null}
                canEditTrip={false}
            />
        </MemoryRouter>,
    )
    expect(screen.getByText('Sign Up Free')).toBeInTheDocument()
})

test('does not render a SignUp CTA if the trip has been generated by a guest visitor', () => {
    render(
        <MemoryRouter initialEntries={['/trip/1']}>
            <TripHeader tripName="Test Trip" userId="1" canEditTrip={false} />
        </MemoryRouter>,
    )
    expect(screen.queryByText('Sign Up Free')).not.toBeInTheDocument()
})

test('renders a Save Changes button if the trip has been generated by a user', () => {
    render(
        <MemoryRouter initialEntries={['/trip/1']}>
            <TripHeader tripName="Test Trip" userId="1" canEditTrip={true} />
        </MemoryRouter>,
    )
    expect(screen.getByText('Save Changes')).toBeInTheDocument()
})

test('does not render a Save Changes button if the trip has been generated by a guest visitor', () => {
    render(
        <MemoryRouter initialEntries={['/trip/1']}>
            <TripHeader
                tripName="Test Trip"
                userId={null}
                canEditTrip={false}
            />
        </MemoryRouter>,
    )
    expect(screen.queryByText('Save Changes')).not.toBeInTheDocument()
})
