name: Merge Develop to Main

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    merge-to-main:
        runs-on: ubuntu-latest
        env:
            ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
            MOONDREAM_API_KEY: ${{ secrets.MOONDREAM_API_KEY }}
            WEB_URL: ${{ secrets.WEB_URL }}
        steps:
            - name: Checkout develop branch
              uses: actions/checkout@v4
              with:
                  ref: develop

            - name: Cache npm dependencies
              uses: actions/cache@v3
              id: npm-cache
              with:
                  path: |
                      ~/.npm
                      node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              if: steps.npm-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Install playwright
              run: npx playwright install chromium

            - name: Run e2e tests
              uses: GabrielBB/xvfb-action@v1
              with:
                  run: npx magnitude -p

            - name: Merge develop -> main
              uses: devmasx/merge-branch@master
              with:
                  type: now
                  from_branch: develop
                  target_branch: main
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  message: 'Automated merge from develop to main'

            - name: Trigger production deployment
              uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  event-type: merge_to_main
                  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
